In [2]:
import pickle
pickle.HIGHEST_PROTOCOL = 4
import pandas as pd

<h1>Get OG stim file<h1>

In [18]:
og_path = "C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5c\\Lib\\site-packages\\pandastim\\resources\\protocols\\fourstim.hdf"
pd.read_hdf(og_path)

    stim_name angle velocity stim_type  stationary_time  duration
0       right    90     0.02         s                3        35
1    backward   180     0.02         s                3        35
2        left   270     0.02         s                3        35
3     forward     0     0.02         s                3        35
4       right    90     0.02         s                3        35
..        ...   ...      ...       ...              ...       ...
275   forward     0     0.02         s                3        35
276     right    90     0.02         s                3        35
277  backward   180     0.02         s                3        35
278      left   270     0.02         s                3        35
279   forward     0     0.02         s                3        35

[280 rows x 6 columns]

In [19]:
og = pd.read_hdf(og_path)

<h1>Make overlapping stim file<h1>

In [61]:
dot = {'stim_name': ['right_dot'],
          'angle': [90],
          'velocity': [0.02],
          'stim_type': ['s'],
          'stationary_time': [3],
          'duration': [35],
           'texture': ['gray_circle'],
          'center': [[-100, 20]]}
dot_df = pd.DataFrame.from_dict(dot)

lateral_right = {'stim_name': ['lateral_right'],
          'angle': [(270, 90)],
          'velocity': [(0, 0.02)],
          'stim_type': ['b'],
          'stationary_time': [3],
          'duration': [35],
           'texture': ['grating_rgb'],
                 'center': [([0,0], [0,0])]}
lateral_right_df = pd.DataFrame.from_dict(lateral_right)

In [62]:
new = pd.DataFrame()
og['texture'] =  ['grating_rgb'] * len(og)
og['center'] =  [[0, 0]] * len(og)
for wholefield_row in og.index:
    wholefield_df = og.loc[wholefield_row]
    mask = {'stim_name': [[dot['stim_name'][0], wholefield_df['stim_name']]],
          'angle': [[dot['angle'][0], wholefield_df['angle']]],
          'velocity': [[dot['velocity'][0], wholefield_df['velocity']]],
          'stim_type': [['m', 'm']],
          'stationary_time': [[dot['stationary_time'][0], wholefield_df['stationary_time']]],
          'duration': [wholefield_df['duration']],
            'texture': [[dot['texture'][0], wholefield_df['texture']]],
            'center': [[dot['center'][0], wholefield_df['center']]]}
    mask_df = pd.DataFrame.from_dict(mask)
    new = pd.concat([new, lateral_right_df,pd.DataFrame(og.loc[wholefield_row]).T, dot_df, mask_df], axis=0).reset_index(drop = True)
    #new = pd.concat([new, mask_df, dot_df], axis=0).reset_index(drop = True)

In [63]:
new

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,center
0,lateral_right,"(270, 90)","(0, 0.02)",b,3,35,grating_rgb,"([0, 0], [0, 0])"
1,right,90,0.02,s,3,35,grating_rgb,"[0, 0]"
2,right_dot,90,0.02,s,3,35,gray_circle,"[-100, 20]"
3,"[right_dot, right]","[90, 90]","[0.02, 0.02]","[m, m]","[3, 3]",35,"[gray_circle, grating_rgb]","[[-100, 20], [0, 0]]"
4,lateral_right,"(270, 90)","(0, 0.02)",b,3,35,grating_rgb,"([0, 0], [0, 0])"
...,...,...,...,...,...,...,...,...
1115,"[right_dot, left]","[90, 270]","[0.02, 0.02]","[m, m]","[3, 3]",35,"[gray_circle, grating_rgb]","[[-100, 20], [0, 0]]"
1116,lateral_right,"(270, 90)","(0, 0.02)",b,3,35,grating_rgb,"([0, 0], [0, 0])"
1117,forward,0,0.02,s,3,35,grating_rgb,"[0, 0]"
1118,right_dot,90,0.02,s,3,35,gray_circle,"[-100, 20]"
1119,"[right_dot, forward]","[90, 0]","[0.02, 0.02]","[m, m]","[3, 3]",35,"[gray_circle, grating_rgb]","[[-100, 20], [0, 0]]"

In [64]:
new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5c\\Lib\\site-packages\\pandastim\\resources\\protocols\\overlap_stim.hdf", key = 'stimulus',  mode = 'w')

C:\Users\Naumann_Lab\AppData\Local\Temp\ipykernel_10628\3215509447.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['stim_name', 'angle', 'velocity', 'stim_type', 'stationary_time',
       'duration', 'texture', 'center'],
      dtype='object')]

  new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5c\\Lib\\site-packages\\pandastim\\resources\\protocols\\overlap_stim.hdf", key = 'stimulus',  mode = 'w')

<h1>Modify stim file<h1>

In [17]:
new = og[og['stim_name'].isin(['forward', 'left', 'right', 'backward'])].reset_index(drop=True)

In [64]:
new.dtypes

stim_name          object
angle              object
velocity           object
stim_type          object
stationary_time    object
duration           object
dtype: object

In [9]:
new =new.convert_dtypes(object, convert_string = False, convert_floating = False)#= new.astype(object)

In [18]:
new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5m\\Lib\\site-packages\\pandastim\\resources\\fourstim.hdf", key = 'stimulus',  mode = 'w')

C:\Users\Naumann_Lab\AppData\Local\Temp\ipykernel_2304\3568714911.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['stim_name', 'angle', 'velocity', 'stim_type'], dtype='object')]

  new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5m\\Lib\\site-packages\\pandastim\\resources\\fourstim.hdf", key = 'stimulus',  mode = 'w')

In [19]:
pd.read_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5m\\Lib\\site-packages\\pandastim\\resources\\fourstim.hdf")

    stim_name angle velocity stim_type  stationary_time  duration
0       right    90     0.02         s                3        35
1    backward   180     0.02         s                3        35
2        left   270     0.02         s                3        35
3     forward     0     0.02         s                3        35
4       right    90     0.02         s                3        35
..        ...   ...      ...       ...              ...       ...
275   forward     0     0.02         s                3        35
276     right    90     0.02         s                3        35
277  backward   180     0.02         s                3        35
278      left   270     0.02         s                3        35
279   forward     0     0.02         s                3        35

[280 rows x 6 columns]