In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
import pickle
pickle.HIGHEST_PROTOCOL = 4
import pandas as pd
import numpy as np
from utils import dot_generator

<h1>Get OG stim file<h1>

In [45]:
og_path = "C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig5z\\Lib\\site-packages\\pandastim\\resources\\protocols\\overlap_stim_241107.hdf"
pd.read_hdf(og_path)

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius
0,"[dot_l_cls_s, left_s]","[90, 270]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
1,"[dot_l_cls_s, left_m]","[90, 270]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
2,"[dot_l_cls_s, right_m]","[90, 90]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
3,"[dot_l_cls_s, forward_m]","[90, 0]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
4,"[dot_l_cls_s, backward_m]","[90, 180]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
...,...,...,...,...,...,...,...,...,...
565,"[dot_l_cls_s, left_m]","[90, 270]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
566,"[dot_l_cls_s, right_m]","[90, 90]","[0.05321356406289263, 0.08]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
567,"[dot_l_cls_s, stationary_left_f]","[90, 270]","[0.05321356406289263, 0.16]","[m, m]","[5, 15]",15,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]"
568,blank,0,0,s,10,10,blank_tex,"[0, 0]",0
569,blank,0,0,s,10,10,blank_tex,"[0, 0]",0

In [ ]:
og = pd.read_hdf(og_path)

<h1>Make Dot Stim Files<H1>

In [ ]:
#left and right offset
far_y = -520#-358
cls_y = -260#-179
#offset from the fish head
l_far_x = 150
r_far_x = -150
l_cls_x = 75
r_cls_x = -75
far_l_radius = 6.5
far_m_radius= 3.9
far_s_radius= 1.3
cls_l_radius = 3.3
cls_m_radius= 2.0
cls_s_radius= 0.7
far_velocity = 0.107
cls_velocity = 0.053
#always 90 for dots
l_angle = 90
r_angle = -90

stationary_time = 1
duration = 10


dot_l_far_l = {'stim_name': ['dot_l_far_l'], 'angle': [l_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, l_far_x]], 'circle_radius': [far_l_radius],}
dot_l_far_l_df = pd.DataFrame.from_dict(dot_l_far_l)
dot_l_far_m = {'stim_name': ['dot_l_far_m'], 'angle': [l_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, l_far_x]], 'circle_radius': [far_m_radius],}
dot_l_far_m_df = pd.DataFrame.from_dict(dot_l_far_m)
dot_l_far_s = {'stim_name': ['dot_l_far_s'], 'angle': [l_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, l_far_x]], 'circle_radius': [far_s_radius],}
dot_l_far_s_df = pd.DataFrame.from_dict(dot_l_far_s)

dot_l_cls_l = {'stim_name': ['dot_l_cls_l'], 'angle': [l_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, l_cls_x]], 'circle_radius': [cls_l_radius],}
dot_l_cls_l_df = pd.DataFrame.from_dict(dot_l_cls_l)
dot_l_cls_m = {'stim_name': ['dot_l_cls_m'], 'angle': [l_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, l_cls_x]], 'circle_radius': [cls_m_radius],}
dot_l_cls_m_df = pd.DataFrame.from_dict(dot_l_cls_m)
dot_l_cls_s = {'stim_name': ['dot_l_cls_s'], 'angle': [l_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, l_cls_x]], 'circle_radius': [cls_s_radius],}
dot_l_cls_s_df = pd.DataFrame.from_dict(dot_l_cls_s)

dot_r_far_l = {'stim_name': ['dot_r_far_l'], 'angle': [r_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, r_far_x]], 'circle_radius': [far_l_radius],}
dot_r_far_l_df = pd.DataFrame.from_dict(dot_r_far_l)
dot_r_far_m = {'stim_name': ['dot_r_far_m'], 'angle': [r_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, r_far_x]], 'circle_radius': [far_m_radius],}
dot_r_far_m_df = pd.DataFrame.from_dict(dot_r_far_m)
dot_r_far_s = {'stim_name': ['dot_r_far_s'], 'angle': [r_angle], 'velocity': [far_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[far_y, r_far_x]], 'circle_radius': [far_s_radius],}
dot_r_far_s_df = pd.DataFrame.from_dict(dot_r_far_s)

dot_r_cls_l = {'stim_name': ['dot_r_cls_l'], 'angle': [r_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, r_cls_x]], 'circle_radius': [cls_l_radius],}
dot_r_cls_l_df = pd.DataFrame.from_dict(dot_r_cls_l)
dot_r_cls_m = {'stim_name': ['dot_r_cls_m'], 'angle': [r_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, r_cls_x]], 'circle_radius': [cls_m_radius],}
dot_r_cls_m_df = pd.DataFrame.from_dict(dot_r_cls_m)
dot_r_cls_s = {'stim_name': ['dot_r_cls_s'], 'angle': [r_angle], 'velocity': [cls_velocity],
               'stim_type': ['s'], 'stationary_time': [stationary_time], 'duration': [duration],
                'texture': ['gray_circle'], 'circle_center': [[cls_y, r_cls_x]], 'circle_radius': [cls_s_radius],}
dot_r_cls_s_df = pd.DataFrame.from_dict(dot_r_cls_s)

In [ ]:
new = pd.concat([dot_l_far_l_df, dot_l_far_m_df, dot_l_far_s_df, dot_l_cls_l_df, dot_l_cls_m_df, dot_l_cls_s_df,
                 dot_r_far_l_df, dot_r_far_m_df, dot_r_far_s_df, dot_r_cls_l_df, dot_r_cls_m_df, dot_r_cls_s_df], axis=0).reset_index(drop = True)

In [ ]:
new = new.sample(frac=30, replace=True, random_state=1).reset_index(drop = True)

In [ ]:
new_blank.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig6z\\Lib\\site-packages\\pandastim\\resources\\protocols\\dot_stim.hdf", key = 'stimulus',  mode = 'w')

<h1>Make overlapping stim file<h1>

In [48]:
#smallest stimulus
dot_name = 'dot_l_cls_s'
dot_side = 'left'
stationary_time = 5
duration = 15
dot_size_deg = 3
y_offset_px = 75
x_offset_px = -260
velocity_deg = 36
canvas_size = 1024
dot_l_cls_s = dot_generator(dot_name, dot_side, dot_size_deg, x_offset_px, y_offset_px, velocity_deg, canvas_size, stationary_time, duration)
dot_name = 'dot_l_cls_m'
# dot_size_deg = 10
# dot_l_cls_m = dot_generator(dot_name, dot_side, dot_size_deg, x_offset_px, y_offset_px, velocity_deg, canvas_size, stationary_time, duration)
# dot_name = 'dot_l_cls_l'
# dot_size_deg = 20
# dot_l_cls_l = dot_generator(dot_name, dot_side, dot_size_deg, x_offset_px, y_offset_px, velocity_deg, canvas_size, stationary_time, duration)

In [49]:
dot_dfs = pd.concat([dot_l_cls_s], axis = 0)
dot_dfs['frequency'] = 12
dot_dfs

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,dot_l_cls_s,90,0.053214,s,5,15,gray_circle,"[-260, 75]",1.965292,12

In [50]:
blank_df = dot_r_far_m = {'stim_name': ['blank'], 'angle': [0], 'velocity': [0],
               'stim_type': ['s'], 'stationary_time': [10], 'duration': [10],
                'texture': ['blank_tex'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [12]}
blank_df = pd.DataFrame.from_dict(blank_df)

In [51]:
forward_df = {'stim_name': ['forward_s'], 'angle': [0], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [6]}
forward_df = pd.DataFrame.from_dict(forward_df)

backward_df = {'stim_name': ['backward_s'], 'angle': [180], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [6]}
backward_df = pd.DataFrame.from_dict(backward_df)

left_df = {'stim_name': ['left_s'], 'angle': [270], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [6]}
left_df = pd.DataFrame.from_dict(left_df)

right_df = {'stim_name': ['right_s'], 'angle': [90], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [6]}
right_df = pd.DataFrame.from_dict(right_df)

wholefield_dfs_s = pd.concat([forward_df, backward_df, left_df, right_df])
wholefield_dfs_s

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,forward_s,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,backward_s,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,left_s,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,right_s,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,6

In [52]:
forward_df = {'stim_name': ['forward_m'], 'angle': [0], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [12]}
forward_df = pd.DataFrame.from_dict(forward_df)

backward_df = {'stim_name': ['backward_m'], 'angle': [180], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [12]}
backward_df = pd.DataFrame.from_dict(backward_df)

left_df = {'stim_name': ['left_m'], 'angle': [270], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [12]}
left_df = pd.DataFrame.from_dict(left_df)

right_df = {'stim_name': ['right_m'], 'angle': [90], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [12]}
right_df = pd.DataFrame.from_dict(right_df)

wholefield_dfs_m = pd.concat([forward_df, backward_df, left_df, right_df])
wholefield_dfs_m

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,forward_m,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,backward_m,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,left_m,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,right_m,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,12

In [53]:
forward_df = {'stim_name': ['forward_f'], 'angle': [0], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [24]}
forward_df = pd.DataFrame.from_dict(forward_df)

backward_df = {'stim_name': ['backward_f'], 'angle': [180], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [24]}
backward_df = pd.DataFrame.from_dict(backward_df)

left_df = {'stim_name': ['left_f'], 'angle': [270], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [24]}
left_df = pd.DataFrame.from_dict(left_df)

right_df = {'stim_name': ['right_f'], 'angle': [90], 'velocity': [0.02],
               'stim_type': ['s'], 'stationary_time': [5], 'duration': [15],
                'texture': ['grating_rgb'], 'circle_center': [[0, 0]], 'circle_radius': [0], 'frequency': [24]}
right_df = pd.DataFrame.from_dict(right_df)

wholefield_dfs_f = pd.concat([forward_df, backward_df, left_df, right_df])
wholefield_dfs_f

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,forward_f,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,backward_f,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,left_f,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,right_f,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,24

In [54]:
wholefield_dfs = pd.concat([wholefield_dfs_s, wholefield_dfs_m, wholefield_dfs_f])
wholefield_dfs

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,forward_s,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,backward_s,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,left_s,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,right_s,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,6
0,forward_m,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,backward_m,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,left_m,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,right_m,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,12
0,forward_f,0,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,backward_f,180,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,left_f,270,0.02,s,5,15,grating_rgb,"[0, 0]",0,24
0,right_f,90,0.02,s,5,15,grating_rgb,"[0, 0]",0,24

In [55]:
new = blank_df
for wholefield_df in wholefield_dfs.iterrows():
    wholefield_df = pd.Series(wholefield_df[1])
    for dot_df in dot_dfs.iterrows():
        dot_df = dot_df[1]
        stationarywf_dot_df = {'stim_name': [[dot_df['stim_name'], 'stationary_'+wholefield_df['stim_name']]],
              'angle': [[dot_df['angle'], wholefield_df['angle']]],
              'velocity': [[dot_df['velocity'], wholefield_df['velocity']]],
              'stim_type': [['m', 'm']],
              'stationary_time': [[stationary_time, duration]],
              'duration': [duration],
                'texture': [[dot_df['texture'], wholefield_df['texture']]],
                'circle_center': [[dot_df['circle_center'], wholefield_df['circle_center']]],
                 'circle_radius': [[dot_df['circle_radius'], wholefield_df['circle_radius']]],
                'frequency': [[dot_df['frequency'], wholefield_df['frequency']]]}
        stationarywf_dot_df = pd.DataFrame.from_dict(stationarywf_dot_df)
        wf_dot_df = {'stim_name': [[dot_df['stim_name'], wholefield_df['stim_name']]],
              'angle': [[dot_df['angle'], wholefield_df['angle']]],
              'velocity': [[dot_df['velocity'], wholefield_df['velocity']]],
              'stim_type': [['m', 'm']],
              'stationary_time': [[10, 5]],
              'duration': [20],
                'texture': [[dot_df['texture'], wholefield_df['texture']]],
                'circle_center': [[dot_df['circle_center'], wholefield_df['circle_center']]],
                 'circle_radius': [[dot_df['circle_radius'], wholefield_df['circle_radius']]],
                     'frequency': [[dot_df['frequency'], wholefield_df['frequency']]]}
        wf_dot_df = pd.DataFrame.from_dict(wf_dot_df)
        if 'forward' in wholefield_df['stim_name'] or 'left' in wholefield_df['stim_name']:
            new = pd.concat([new, stationarywf_dot_df, wf_dot_df], axis = 0).reset_index(drop = True)
        else:
            new = pd.concat([new, wf_dot_df], axis = 0).reset_index(drop = True)

In [56]:
new = new.sample(frac=30, replace=True, random_state=1).reset_index(drop = True)
new

,stim_name,angle,velocity,stim_type,stationary_time,duration,texture,circle_center,circle_radius,frequency
0,"[dot_l_cls_s, left_s]","[90, 270]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 6]"
1,"[dot_l_cls_s, left_m]","[90, 270]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
2,"[dot_l_cls_s, right_m]","[90, 90]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
3,"[dot_l_cls_s, forward_m]","[90, 0]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
4,"[dot_l_cls_s, backward_m]","[90, 180]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
...,...,...,...,...,...,...,...,...,...,...
565,"[dot_l_cls_s, left_m]","[90, 270]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
566,"[dot_l_cls_s, right_m]","[90, 90]","[0.05321356406289263, 0.02]","[m, m]","[10, 5]",20,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 12]"
567,"[dot_l_cls_s, stationary_left_f]","[90, 270]","[0.05321356406289263, 0.02]","[m, m]","[5, 15]",15,"[gray_circle, grating_rgb]","[[-260, 75], [0, 0]]","[1.9652917231140454, 0]","[12, 24]"
568,blank,0,0,s,10,10,blank_tex,"[0, 0]",0,12
569,blank,0,0,s,10,10,blank_tex,"[0, 0]",0,12

In [58]:
new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig6z\\Lib\\site-packages\\pandastim\\resources\\protocols\\overlap_stim_241120.hdf", key = 'stimulus',  mode = 'w')

C:\Users\Naumann_Lab\AppData\Local\Temp\ipykernel_11124\1284304532.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block1_values] [items->Index(['stim_name', 'angle', 'velocity', 'stim_type', 'stationary_time',
       'texture', 'circle_center', 'circle_radius', 'frequency'],
      dtype='object')]

  new.to_hdf("C:\\Users\\Naumann_Lab\\Miniconda3\\envs\\rig6z\\Lib\\site-packages\\pandastim\\resources\\protocols\\overlap_stim_241120.hdf", key = 'stimulus',  mode = 'w')